version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ldflags:
      - >-
        -s -w
      - -X 'github.com/macaroni-os/anise-repo-devkit/pkg/devkit.BuildTime={{ time "2006-01-02 15:04:05 MST" }}'
      - -X 'github.com/macaroni-os/anise-repo-devkit/pkg/devkit.BuildCommit={{ .FullCommit }}'
      - -X 'github.com/macaroni-os/anise-repo-devkit/pkg/devkit.BuildGoVersion={{ .Env.GOVERSION }}'

archives:
  - format: binary
    name_template: anise-repo-devkit-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^scripts:'
      - '^Merge'
